KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_randomClient="the_clients_secret_i_guess"
    serviceName="kafka";
};
