{
 "title": "Confluent RBAC",
 "description": "Monitor Confluent RBAC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_connect_app_info,env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_replicamanager_leadercount{env=\"${env}\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RBAC and LDAP metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Writers for MDS",
   "type": "gauge",
   "description": "Number of active writers in the metadata cluster. Alert if the sum is any number other than one because there should be exactly one writer in the metadata cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_metadata_kafkaauthstore{job=\"kafka-broker\", env=\"$env\", name=\"active-writer-count\"})"
    }
   ]
  },
  {
   "title": "Role Bindings Count",
   "type": "gauge",
   "description": "The number of role bindings defined. This metric is useful in cases where you need to know the exact number of role bindings that exist.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(confluent_auth_store_metrics_rbac_role_bindings_count{job=\"kafka-broker\", instance=~\"$instance\", env=\"$env\"}) by (instance))"
    }
   ]
  },
  {
   "title": "rbac-access-rules-count",
   "type": "timeseries",
   "description": "The number of RBAC access rules defined. This metric is useful in cases where you need to know the exact number of RBAC access rules that exist. Access rules allow or deny access to specific resources within a specific scope, unlike role bindings, which assign an RBAC role for a specific resource to a specific principal.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_auth_store_metrics_rbac_access_rules_count{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "acl-access-rules-count",
   "type": "timeseries",
   "description": "The number of ACL access rules defined. This metric is useful in cases where you need to know the exact number of ACLs that exist.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_auth_store_metrics_acl_access_rules_count{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "reader-failure-start-seconds-ago",
   "type": "timeseries",
   "description": "The number of seconds since the last failure in the consumer that processes authentication or authorization metadata from the topics in the metadata cluster. This is reset to zero after the next successful metadata refresh. This metric is available on all brokers configured to use RBAC. Alert if value is greater than zero.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_metadata_kafkaauthstore{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\", name=\"reader-failure-start-seconds-ago\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "failure-start-seconds-ago",
   "type": "timeseries",
   "description": "The number of seconds since the last failed attempt to process metadata from the LDAP server. This is reset to zero on the next successful metadata refresh. This metric is available on brokers in the metadata cluster if LDAP group-based authorization is enabled. Alert if value is greater than zero.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_metadata_ldapgroupmanager{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\", name=\"failure-start-seconds-ago\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "record-send-rate",
   "type": "timeseries",
   "description": "The average number of records sent per second to the metadata topic partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_metadata_kafkaauthstore{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\", name=\"record-send-rate\"}",
     "legendFormat": "{{instance}} - {{topic}} - {{partition}}"
    }
   ]
  },
  {
   "title": "writer-failure-start-seconds-ago",
   "type": "timeseries",
   "description": "The number of seconds since the last failure in the writer that updates authentication or authorization metadata on topics in the metadata cluster. This is reset to zero after the next successful metadata update. This metric is available on brokers in the metadata cluster. Alert if value is greater than zero.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_metadata_kafkaauthstore{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\", name=\"writer-failure-start-seconds-ago\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "remote-failure-start-seconds-ago",
   "type": "timeseries",
   "description": "The number of seconds since the last failure in the metadata service, for example, due to LDAP refresh failures for a long duration. This is reset to zero when notification of successful refresh from the metadata service is processed. This metric is available on all brokers configured to use RBAC. Alert if value is greater than zero.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_metadata_kafkaauthstore{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\", name=\"remote-failure-start-seconds-ago\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "record-error-rate",
   "type": "timeseries",
   "description": "The average number of record send attempts per second to the metadata topic partitions that failed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_metadata_kafkaauthstore{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\", name=\"record-error-rate\"}",
     "legendFormat": "{{instance}} - {{topic}} - {{partition}}"
    }
   ]
  }
 ]
}