{
 "title": "Kafka Consumer",
 "description": "Kafka Consumer Java client metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "label": "Client ID",
    "query": {
     "query": "label_values(kafka_consumer_app_info, client_id)"
    }
   },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "consumer_group",
    "label": "Group ID",
    "query": {
     "query": "label_values(kafka_consumergroup_group_lag, group)"
    }
   },
   { "name": "topic", "label": "topic", "query": { "query": "label_values(topic)" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(kafka_consumer_app_info, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Key metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Disclaimer\n\n⚠️ This dashboard has some sample thresholds, this example is not meant to fit all use cases nor is it meant for production. Think of it as a learning tool to help you become comfortable with the metrics and thresholding.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit rate",
   "type": "stat",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_failed_authentication_rate{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "stat",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_rate_per_hour{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"} + kafka_consumer_consumer_coordinator_metrics_failed_rebalance_rate_per_hour{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{env=\"$env\",hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{job}}@{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{env=\"$env\",hostname=~\"$hostname\"})",
     "legendFormat": "{{job}}@{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\",area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{env=\"$env\",hostname=~\"$hostname\"}[5m]))",
     "legendFormat": "{{job}}@{{instance}}"
    }
   ]
  },
  { "title": "Consumer Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Consumer Lag Offsets - Per Topic",
   "type": "timeseries",
   "description": "The difference between the last offset stored by the broker and the last committed offset for a specific consumer group name, client ID, member ID, group instance ID, topic name, and partition ID\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname, consumergroup, topic) (kafka_server_tenant_metrics_consumer_lag_offsets{client_id=~\"$client_id\", env=\"$env\", topic=~\"$topic\", consumergroup=~\"$consumer_group\"})",
     "legendFormat": "{{consumergroup}}@{{hostname}}@{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Lag Offsets - Per Partition",
   "type": "timeseries",
   "description": "The difference between the last offset stored by the broker and the last committed offset for a specific consumer group name, client ID, member ID, group instance ID, topic name, and partition ID\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_tenant_metrics_consumer_lag_offsets{client_id=~\"$client_id\", env=\"$env\", topic=~\"$topic\", consumergroup=~\"$consumer_group\"}",
     "legendFormat": "{{consumergroup}}@{{hostname}}@{{topic}}@{{partition}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bytes consumed rate",
     "type": "timeseries",
     "description": "The average number of bytes consumed per second\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic=~\"$topic\", client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Rate of records consumed",
     "type": "timeseries",
     "description": "The average number of records consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{topic=~\"$topic\", client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Bytes consumed rate per topic",
     "type": "timeseries",
     "description": "The average number of bytes consumed per topic per second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic!=\"\", client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Rate of records consumed per topic",
     "type": "timeseries",
     "description": "The average number of records consumed per second per topic.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (topic) (rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{topic!=\"\", client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Fetch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Fetch request rate",
     "type": "timeseries",
     "description": "The number of fetch requests per second.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_fetch_total{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}[$__rate_interval])",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Fetch size avg",
     "type": "timeseries",
     "description": "The average number of bytes fetched per request for a topic",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{topic=~\"$topic\", client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
       "legendFormat": "{{client_id}}@{{hostname}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Fetch latency average",
     "type": "timeseries",
     "description": "The average time taken for a fetch request.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Commit Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Commit latency average",
     "type": "timeseries",
     "description": "The average time taken for a commit request",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_avg{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Commit rate",
     "type": "timeseries",
     "description": "The number of commit calls per second .",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current connection count",
     "type": "timeseries",
     "description": "Number of simultaneous connections\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_count{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Node reponse rate",
     "type": "timeseries",
     "description": "response rate per node\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_response_rate{client_id=~\"$client_id\", env=\"$env\",hostname=~\"$hostname\"}",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}